In [1]:
import pandas as pd

In [2]:
ages = pd.Series([23,66,55,88,2,11,44,9,77,100,101,102,33,55,22,19,70],name="Age")
ages

0      23
1      66
2      55
3      88
4       2
5      11
6      44
7       9
8      77
9     100
10    101
11    102
12     33
13     55
14     22
15     19
16     70
Name: Age, dtype: int64

In [3]:
ages.max()

np.int64(102)

In [4]:
ages.describe()

count     17.000000
mean      51.588235
std       34.411224
min        2.000000
25%       22.000000
50%       55.000000
75%       77.000000
max      102.000000
Name: Age, dtype: float64

In [31]:
ages.shape

(17,)

In [28]:
# Read Data from a CSV File 
staff_data = pd.read_csv("../Fetch_API_Data/first_5_staffs.csv")
df = pd.DataFrame(staff_data)
df

  first_name     last_name  department    salary  employee_id
0    Olivier      Caldwell     Finance  88562.80            1
1   Augustin  Cholmondeley  Operations  32702.03            2
2    Adolphe        Hiscoe   Marketing  51209.14            3
3     Louise       Bellham          HR  34115.51            4
4    Hilario       Boshell          HR  70539.22            5

In [29]:
# Get the rows in the first_name column
df["first_name"].shape

(5,)

In [ ]:
# Get the Data Types of the columns
df.dtypes

first_name         str
last_name          str
department         str
salary         float64
employee_id      int64
dtype: object

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   first_name   5 non-null      str
 1   last_name    5 non-null      str
 2   department   5 non-null      str
 3   salary       5 non-null      float64
 4   employee_id  5 non-null      int64
dtypes: float64(1), int64(1), str(3)
memory usage: 332.0 bytes

In [30]:
# Data from 2 columns
staff_cols = df[["first_name","last_name"]]
type(staff_cols)

pandas.DataFrame

In [39]:
less_sals = df[df["salary"] > 70000]
less_sals

  first_name last_name department    salary  employee_id
0    Olivier  Caldwell    Finance  88562.80            1
4    Hilario   Boshell         HR  70539.22            5

In [46]:
# Select specific Rows and Columns
cap_rows_cols = staff_cols.iloc[1:4, 0:2]
cap_rows_cols

  first_name     last_name
1   Augustin  Cholmondeley
2    Adolphe        Hiscoe
3     Louise       Bellham